services:
  - type: worker
    name: kelvin-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python core.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: GIGACHAT_CREDENTIALS
        sync: false